### ISSUE TITLE
error when i import TerminalMenu

### ISSUE THREAD

**Issue by Jean-PierreBE** [IngoMeyer441/simple-term-menu#71]
hello 
i want to  import TerminalMenu from simple_term_menu like that 

from simple_term_menu import TerminalMenu
i have the following error 

File "C:\Users\stein\PycharmProjects\TournoisEchecs\venv\lib\site-packages\simple_term_menu.py", line 37, in <module>
    import termios
ModuleNotFoundError: No module named 'termios'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\stein\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\stein\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\stein\PycharmProjects\TournoisEchecs\ProjectTournoi\__main__.py", line 8, in <module>
    import ProjectTournoi.Tournoi as tn
  File "C:\Users\stein\PycharmProjects\TournoisEchecs\ProjectTournoi\Tournoi.py", line 3, in <module>
    from simple_term_menu import TerminalMenu
  File "C:\Users\stein\PycharmProjects\TournoisEchecs\venv\lib\site-packages\simple_term_menu.py", line 39, in <module>
    raise NotImplementedError('"{}" is currently not supported.'.format(platform.system())) from e
NotImplementedError: "Windows" is currently not supported.

for information , i am working on windows 10

kind regards

**Comment by IngoMeyer441** [comment]
I am sorry, Windows is currently not supported. See #5 for the related issue.
